### ISSUE TITLE
Speakers on the home page show path on the bottom 

### ISSUE THREAD

**Issue by derkoe** [coding-club-linz/global-azure-bootcamp-2022#3]
For Martin Ulrich for example "\app\organizer\sessions\10798"

![image](https://user-images.githubusercontent.com/123199/233071638-f601c78c-6c6e-4e4a-81f4-7914f0cd2ed6.png)

**Comment by rstropek** [comment]
Hi @derkoe!

I guess you want that feature to be able to promote sessions. We would like to enable that, but a little bit differently. We already created speaker cards (e.g. https://github.com/coding-club-linz/global-azure-bootcamp-2022/blob/main/streaming-assets/cards/png/edge-cloud.png) for each session. Please do **not** use them already, the deep links to the sessions don't work yet. Will be fixed during the coming weekend.

Best,
Rainer.

**Comment by derkoe** [comment]
@rstropek I'm not talking about a feature request.

The text on on the bottom of the card (here "\app\organizer\sessions\10798") is displayed by accident I guess.

**Comment by rstropek** [comment]
@derkoe Ah, I see. We will fix that as soon as possible. Thank you for pointing that out.
